# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - postgres-compose-network  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge