version: "3.8"
services:
  siad-db:
    image: postgres
    restart: always
    ports:
      - 5434:5432

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dwdengue
